oracle-quickstart/oci-cloudnative

- deploy/basic/terraform/atp.tf
Enable support for always free database instances
> Enable Always Free tier  ATP database support

- README.md
- deploy/basic/README.md
- deploy/basic/terraform/storage.tf
- src/catalogue/README.md
- src/catalogue/cmd/cataloguesvc/main.go
- src/catalogue/docker/docker-compose-zipkin.yml
- src/catalogue/docker/docker-compose.yml
- src/catalogue/service.go
Patch update.
Includes:
- Object Storage lifecycle for deployment assets
- README fixes
- Version bumped to v1.0.1
- catalogue cleanup
- catalogue local zipkin
> deploy_assets_lifecycle_plus_fixes

- deploy/basic/terraform/policy.tf
added a unique identifier for the policy name
> added a unique identifier for the policy  name

- deploy/basic/README.md
$PWD isn't supported under powershell
> Update README.md for Windows Powershell

- README.md
Includes README changes to point to v1.0.3-basic stack.
Changes on the services and terraform scripts covered by previous commits.
> README update for v1.0.3-basic

- src/docs/source/includes/_deployment.md
Move warning bellow ```shell entry
> Fix style broken when using <aside call=

- src/catalogue/README.md
- src/catalogue/THIRDPARTY.md
- src/catalogue/go.mod
- src/catalogue/go.sum
- src/catalogue/service_test.go
Basic Unit tests for service.go. 80% Coverage.
> unit tests for catalogue service

- src/docs/source/javascripts/app/_clipboard.js
- Prevents automatic execution when pasted into terminal
> fix copy with carriage return

- README.md
> Resolve resource manager stack instruction

- deploy/complete/helm-chart/mushop/charts/api/templates/api-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/assets/templates/assets-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/carts/templates/carts-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/catalogue/templates/catalogue-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/edge/templates/edge-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/events/templates/events-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/fulfillment/templates/fulfillment-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/nats/templates/nats-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/orders/templates/orders-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/payment/templates/payment-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/session/templates/session-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/storefront/templates/storefront-deployment.yaml
- deploy/complete/helm-chart/mushop/charts/user/templates/user-deployment.yaml
Fix to allow `helm upgrade ...` to actually work for managing the releases
> removed immutable version matchlabel

- deploy/complete/helm-chart/provision/README.md
- src/catalogue/kubernetes/README.md
- src/docs/source/includes/_cleanup.md
- src/docs/source/includes/_deployment.md
readmes and /docs updated to use osb 1.4.0 (tested)
> docs_updated_osb_1.4.0

- .github/workflows/docs.yml
- .github/workflows/test-docs.yml
New actions for the _incoming_ hugo docs
> Feature: hugo docs ci

- deploy/complete/helm-chart/mushop/charts/assets/templates/deploy-job.yaml
- deploy/complete/helm-chart/mushop/charts/assets/templates/destroy-job.yaml
- deploy/complete/helm-chart/mushop/charts/carts/templates/carts-job.yaml
- deploy/complete/helm-chart/mushop/charts/catalogue/templates/catalogue-job.yaml
- deploy/complete/helm-chart/mushop/charts/orders/templates/orders-job.yaml
- deploy/complete/helm-chart/mushop/charts/user/templates/user-job.yaml
- deploy/complete/kubernetes/manifests/user-initdb-job.yaml
- deploy/complete/kubernetes/manifests/user-syncdb-job.yaml
- src/docs/content/extras/istio.md
- src/user/kubernetes/init-job.yaml
- src/user/kubernetes/sync-job.yaml
> Don't inject sidecars to init containers

- deploy/complete/docker-compose/docker-compose.yml
- deploy/complete/helm-chart/mushop/charts/carts/values.yaml
- deploy/complete/kubernetes/manifests/carts-dep.yaml
Follow up to #149 
CC @jjspiegel
> bump carts in helm chart

- src/docs/content/cloud/deployment.md
> fix to update osb to ver 1.4.0

- src/docs/content/extras/canary.md
This is a bug fix PR. There was a formatting (spacing) issue with shell commands. corrected the doc.
> Correcting minor linux shell formatting issue

- src/storefront/gulpfile.js
fixes Issue with build in cloud shell environment. gives graceful failure of image optimization
> graceful fail imagemin in CS environment

- README.md
- deploy/basic/README.md
- deploy/complete/README.md
Enable magic buttons to Deploy to OCI.
---
Merge to Master contingent to a specific date.
> Merge Scheduled: Magic buttons

- README.md
Main README changed based on feedback for magic button
> Quick fix readme

- README.md
- deploy/basic/README.md
- deploy/complete/README.md
- src/docs/content/cloud/deployment.md
- src/docs/content/quickstart/basic.md
replaced with one console url for magic buttons and docs references.
> removed region defaults dependency

- src/docs/themes/redwood/package-lock.json
- src/docs/themes/redwood/package.json
> fix uikit version because of 3.6.6 bugs

- deploy/complete/helm-chart/setup/requirements.yaml
- deploy/complete/terraform/mushop-utilities.tf
- deploy/complete/terraform/mushop-variables.tf
- deploy/complete/terraform/oke-variables.tf
- deploy/complete/terraform/schema.yaml
> Mushop oke autoscaler support

- deploy/basic/terraform/.terraform.lock.hcl
- deploy/basic/terraform/network.tf
- deploy/basic/terraform/providers.tf
- deploy/basic/terraform/schema.yaml
- deploy/basic/terraform/terraform.tfvars.example
- deploy/basic/terraform/tf_msz.tfvars.example
- deploy/basic/terraform/variables.tf
- deploy/complete/terraform/.terraform.lock.hcl
- deploy/complete/terraform/providers.tf
Complete:
- Providers lock updated
Basic:
- Providers lock updated
- Lock multi platform enabled
- Versioned providers to keep compatibility of standalone Terraform and ORM (Using old providers)
- Always Free variable updated
> Basic mini patch

- README.md
Resource Manager is under Developer Services
> adapt description to new console menu

- deploy/complete/terraform/oke-autoscaler.tf
> use better local variable name

- src/README.md
> Update src/Readme.md to correct links

- deploy/complete/helm-chart/setup/requirements.yaml
- deploy/complete/helm-chart/setup/templates/NOTES.txt
- deploy/complete/helm-chart/setup/values.yaml
This updates the Jenkins chart version / dependencies used in the mushop-setup namespace
> fixes the Jenkins chart old version dependancies
